# Generated by Django 6.1.1 on 2026-09-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentOnboarding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.CharField(max_length=64, unique=True)),
                ("lsa_id", models.CharField(blank=True, max_length=64)),
                ("guardian_email", models.EmailField(max_length=254)),
                (
                    "onboarding_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("region", models.CharField(max_length=2)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["region"], name="onboarding__region_39330c_idx"
                    ),
                    models.Index(
                        fields=["onboarding_status"],
                        name="onboarding__onboard_693d24_idx",
                    ),
                ],
            },
        ),
    ]
